export const spectacle = {
  title: "SARAU 2026",
  subtitle: "UTOPIA",
  tagline: '"Lugar que não existe"',
  description: "Uma Proposta de Espetáculo Narrativo",
  clube: "Clube de Ginástica dos Bombeiros das Caldas da Rainha",
  arco: ["MUNDO IMPERFEITO", "SILÊNCIO & SONHO", "CONSTRUÇÃO COLETIVA", "FRAGILIDADE", "O INSTANTE PERFEITO"],
};

export const acts = [
  {
    id: 1,
    number: "ATO I",
    title: "A RUTURA",
    subtitle: "O mundo que temos, e a razão pela qual precisamos de sonhar",
    color: "#e53e3e",
    intro: "O sarau não começa na utopia. Começa no seu oposto: a realidade. É este contraste que dá peso e significado a tudo o que se segue. A audiência precisa de sentir o desconforto do presente para valorizar a viagem.",
    scenes: [
      {
        number: 1,
        title: "O MUNDO IMPERFEITO",
        turma: "Turma 13+/15+ (4ª e 6ª)",
        descricao: "O palco abre com luz fria e ritmo denso. A coreografia evoca caos, pressa e desencontro, corpos que se cruzam mas nunca se encontram. Movimentos urgentes e fragmentados. Nenhum sorriso. Esta é a realidade.",
        narracao: '"Acordámos. Corrêmos. Esquecêmos. Voltámos a acordar. Em algum lugar… há um mundo diferente deste. Ainda não o encontrámos. Mas sentimos… que existe."',
        narracaoNota: null,
        musica: 'Massive Attack — "Teardrop" (versão instrumental, com percussão adicionada)',
        musicaUrl: 'https://www.youtube.com/results?search_query=Massive+Attack+Teardrop+instrumental',
        musicaAlt: 'The Chemical Brothers — "Galvanize"',
        musicaAltUrl: 'https://www.youtube.com/results?search_query=The+Chemical+Brothers+Galvanize',
      },
      {
        number: 2,
        title: "O SILÊNCIO ANTES",
        turma: "Abertura I",
        descricao: "A música para abruptamente. Corte total. O palco escurece. Os atletas saem lentamente. Silêncio de 6 a 8 segundos, absoluto. Um único foco de luz ilumina o centro vazio do palco.",
        narracao: '"E se parássemos… só um instante? E se, antes de tudo o mais… houvesse silêncio?"',
        narracaoNota: "voz suave, quase sussurrada, sobre drone mínimo ou silêncio absoluto",
        musica: 'Silêncio, ou sub-bass drone mínimo.',
        musicaUrl: null,
        musicaAlt: 'Arvo Pärt — "Spiegel im Spiegel" (apenas os primeiros 20 segundos)',
        musicaAltUrl: 'https://www.youtube.com/results?search_query=Arvo+P%C3%A4rt+Spiegel+im+Spiegel',
      },
    ],
  },
  {
    id: 2,
    number: "ATO II",
    title: "O DESPERTAR",
    subtitle: "O sonho começa, a perspetiva da criança",
    color: "#3182ce",
    intro: "No sonho, o mundo transforma-se. É o momento da leveza e da possibilidade ilimitada. As turmas mais novas trazem a energia de quem ainda não aprendeu a desistir de imaginar.",
    scenes: [
      {
        number: 3,
        title: "O SONHO DA UTOPIA",
        turma: "Abertura II",
        descricao: "A luz regressa, mas agora quente e difusa. Um único foco no centro do palco. Atmosfera em build-up gradual. É o nascimento do sonho, a promessa do que está prestes a ser descoberto.",
        narracao: '"No princípio, havia um sonho. E no sonho… tudo se tornava possível. Fecha os olhos. Imagina. Como seria o mundo… se fôssemos livres?"',
        narracaoNota: "voz clara, crescente",
        musica: 'Max Richter — "On the Nature of Daylight"',
        musicaUrl: 'https://www.youtube.com/results?search_query=Max+Richter+On+the+Nature+of+Daylight',
        musicaAlt: 'Ludovico Einaudi — "Experience" (abertura)',
        musicaAltUrl: 'https://www.youtube.com/results?search_query=Ludovico+Einaudi+Experience',
      },
      {
        number: 4,
        title: "O DESCOBRIR E O BRINCAR",
        turma: "Turma 7+/8+",
        descricao: "As crianças exploram o espaço com curiosidade pura. Movimentos soltos, orgânicos, imprevisíveis. A energia é de liberdade absoluta, o mundo é novo e tudo é possível. Não há regras.",
        narracao: '"E se o chão fosse uma nuvem? E se pudéssemos ir a qualquer lugar… só de pensar? E se não houvesse regras… só o brincar?"',
        narracaoNota: "voz de criança, pré-gravada",
        musica: 'Yann Tiersen — "Comptine d\'un autre été" (remix contemporâneo)',
        musicaAlt: 'Beirut — "Nantes"',
      },
      {
        number: 5,
        title: "CRIADORES DE MUNDOS",
        turma: "Turma 6/7/8",
        descricao: "Os mais novos. Cada criança \"cria\" algo invisível, esticam os braços, desenham formas no ar, plantam sementes imaginárias. Os pequenos grupos convergem e os mundos que criaram acabam por se unir num só.",
        narracao: '"Eu criei um rio. Ela criou uma floresta. Ele criou uma estrela. E de repente… havia um mundo inteiro."',
        narracaoNota: "múltiplas vozes de crianças sobrepostas",
        musica: 'Nils Frahm — "Says" (início etéreo)',
        musicaAlt: 'Explosions in the Sky — "First Breath After Coma" (abertura)',
      },
    ],
  },
  {
    id: 3,
    number: "ATO III",
    title: "A CONSTRUÇÃO",
    subtitle: "Do indivíduo ao coletivo, juntos, criamos",
    color: "#38a169",
    intro: "A transição do sonho para a ação. A coreografia torna-se mais geométrica, progressiva e sincronizada. A mensagem essencial: a utopia não se encontra. Constrói-se.",
    scenes: [
      {
        number: 6,
        title: "A CONSTRUÇÃO",
        turma: "Turma 9/10/11",
        descricao: "A coreografia torna-se geométrica. Formações precisas, movimentos que se encaixam uns nos outros como peças de um mecanismo. A ideia de que algo maior está a ser construído coletivamente, passo a passo.",
        narracao: '"A utopia não cai do céu. Constrói-se. Tijolo a tijolo. Corpo a corpo. Decisão a decisão. Juntos… criamos algo maior do que nós."',
        narracaoNota: "voz adulta, determinada",
        musica: 'Daft Punk — "Harder, Better, Faster, Stronger"',
        musicaAlt: 'Philip Glass — "Metamorphosis Two" (versão progressiva)',
      },
      {
        number: 7,
        title: "A SINTONIA E A CONEXÃO",
        turma: "Turma 10+/12+",
        descricao: "A coreografia evolui para algo mais fluído e interligado. Os atletas respondem uns aos outros em vez de ao tempo da música, como se partilhassem uma frequência invisível. O coletivo como um organismo vivo.",
        narracao: '"Quando paramos de falar… e começamos a escutar… o movimento nasce por si mesmo. Ligados… somos mais do que a soma das partes."',
        narracaoNota: "voz calma",
        musica: 'Ludovico Einaudi — "Experience"',
        musicaAlt: 'Ólafur Arnalds & Nils Frahm — "Burning"',
      },
    ],
  },
  {
    id: 4,
    number: "ATO IV",
    title: "A FRAGILIDADE",
    subtitle: "O ponto de tensão, o perigo da utopia imposta",
    color: "#d69e2e",
    intro: "O ponto de conflito necessário em qualquer narrativa. Sem este ato, o espetáculo seria linear. A ideia da utopia forjada pela força, a sociedade perfeita que sufoca, cria o contraste que torna a resolução ainda mais poderosa.",
    scenes: [
      {
        number: 8,
        title: "A FRAGILIDADE",
        turma: "Turma 13+/15+ (3ª e 5ª)",
        descricao: "Corte brusco. A luz torna-se fria e dura. A coreografia alterna entre pausas absolutas e movimentos frágeis e tensos. A sonoplastia usa drones e subgraves marcados. Algo que parecia certo… está a rachar.",
        narracao: '"E se alguém decidisse… que a sua utopia… era a única utopia? O silêncio que se segue… não é paz. É o peso de uma liberdade… que foi tirada."',
        narracaoNota: "voz tensa, fragmentada, com pausas longas entre as frases",
        musica: 'Clint Mansell — "Lux Aeterna" (de Requiem for a Dream)',
        musicaAlt: 'Jonny Greenwood — "Popcorn Superhet Receiver" (excerto)',
      },
    ],
  },
  {
    id: 5,
    number: "ATO V",
    title: "O INSTANTE PERFEITO",
    subtitle: "A resolução, a utopia existe aqui, agora",
    color: "#805ad5",
    intro: "A verdadeira mensagem do espetáculo: a utopia não é um lugar perfeito algures no futuro. É um instante. É uma pessoa. É o agora partilhado. O clímax emocional constrói-se neste ato até à cena final.",
    scenes: [
      {
        number: 9,
        title: "A AMIZADE",
        turma: "Esquemas Extras, pares (Matilde/Teresa Rogeiro; Lia/Madalena Leal)",
        descricao: "Depois da tensão do ato anterior, o contraste é absoluto. Dois a dois. Simplicidade. Dois corpos que se conhecem, que se apoiam genuinamente. A coreografia é íntima, quase sussurrada.",
        narracao: '"A utopia não é um lugar sem dor. É ter alguém ao lado… que nos conhece de verdade."',
        narracaoNota: "voz suave",
        musica: 'Erik Satie — "Gymnopédie No.1"',
        musicaAlt: 'Bon Iver — "Skinny Love" (versão piano)',
      },
      {
        number: 10,
        title: "O AGORA E A HARMONIA",
        turma: "Turma 10+/12+ (coreografias O Agora / A Harmonia)",
        descricao: "Movimento fluído, contínuo, como se o tempo tivesse abrandado. O foco está no presente, cada gesto deliberado, cada respiração presente e consciente. O clímax emocional começa a construir.",
        narracao: '"Pára. Sente. Aqui. Agora. Este momento… é o único que existe. E neste momento… somos perfeitos."',
        narracaoNota: "voz presente, respirada, com pausas breves entre cada frase",
        musica: 'Ólafur Arnalds — "Near Light"',
        musicaAlt: 'Nils Frahm — "Says" (segunda metade, crescendo)',
      },
      {
        number: "FINAL",
        title: "O INSTANTE UTÓPICO",
        turma: "Todos — gradualmente, todas as turmas regressam ao palco",
        descricao: "A cena começa com os pares dos Esquemas Extras (Madalena/Sara, Carolina/Teresa). Um a um, os grupos voltam ao palco. As luzes aquecem. A música atinge o clímax. A última narração é dita sobre o crescendo final. Depois silêncio. Depois luz plena. O aplauso nasce naturalmente.",
        narracao: '"A utopia… não está algures no futuro. Não está noutro lugar. Está aqui. Está agora. Está em nós… quando nos movemos juntos."',
        narracaoNota: "múltiplas vozes sobrepostas, adultos e crianças, todas as idades do clube",
        musica: 'Hans Zimmer — "Time" (de Inception) para o crescendo final',
        musicaAlt: 'Sigur Rós — "Hoppípolla" (secção final)',
        isFinal: true,
      },
    ],
  },
];

export const mapaDeСenas = [
  { cena: "1",     titulo: "O Mundo Imperfeito",    turma: "13+/15+ (4ª e 6ª)",      ato: "ATO I" },
  { cena: "2",     titulo: "O Silêncio Antes",       turma: "Abertura I",              ato: "ATO I" },
  { cena: "3",     titulo: "O Sonho da Utopia",      turma: "Abertura II",             ato: "ATO II" },
  { cena: "4",     titulo: "O Descobrir e o Brincar",turma: "7+/8+",                   ato: "ATO II" },
  { cena: "5",     titulo: "Criadores de Mundos",    turma: "6/7/8",                   ato: "ATO II" },
  { cena: "6",     titulo: "A Construção",           turma: "9/10/11",                 ato: "ATO III" },
  { cena: "7",     titulo: "A Sintonia e a Conexão", turma: "10+/12+",                 ato: "ATO III" },
  { cena: "8",     titulo: "A Fragilidade",          turma: "13+/15+ (3ª e 5ª)",      ato: "ATO IV" },
  { cena: "9",     titulo: "A Amizade",              turma: "Esquemas Extras (pares)", ato: "ATO V" },
  { cena: "10",    titulo: "O Agora e a Harmonia",   turma: "10+/12+",                 ato: "ATO V" },
  { cena: "FINAL", titulo: "O Instante Utópico",     turma: "Todos",                   ato: "ATO V" },
];
